CREATE TABLE agentes (
 id BIGSERIAL PRIMARY KEY,
 keycloak_user_id VARCHAR(120) UNIQUE,
 nombres VARCHAR(100) NOT NULL,
 apellidos VARCHAR(100) NOT NULL,
 email VARCHAR(160) NOT NULL UNIQUE,
 telefono VARCHAR(30),
 matricula VARCHAR(80) NOT NULL UNIQUE,
 estado VARCHAR(20) NOT NULL,
 created_at TIMESTAMPTZ NOT NULL,
 updated_at TIMESTAMPTZ NOT NULL
);
